name: omop-lite

services:
  omop-lite:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SCHEMA_NAME=cdm
    volumes:
      - ./data:/data
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=omop
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
