name: 'Check PR title'

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  main:
    uses: health-informatics-uon/workflows/.github/workflows/pr-title.yml@1.5.0
    permissions:
      pull-requests: read
